# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
 workflow_dispatch:
    
jobs:
  build-java:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: nanajanashia/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         
  block_schedule:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'

    steps:
      - name: Block workflow from running during certain times
        run: |
          current_hour=$(date +'%H')
          current_day=$(date +'%u')

          if (( current_day < 6 && current_hour >= 22 )) || (( current_day >= 6 && current_hour >= 21 )); then
            echo "::error::Workflow is blocked from running at this time"
            exit 1
          
          
